ISHTIAQ/Models/Car.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISHTIAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int id { get; set; }
        public string carno { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string available { get; set; }
    }
}

ISHTIAQ/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ISHTIAQ.Models;

namespace ISHTIAQ.Controllers
{
    public class CarsController : Controller
    {
        private CarRegistrationEntities db = new CarRegistrationEntities();

        // GET: Cars
        public ActionResult Index(string SearchBy, string Search)
        {
            if (SearchBy == "Number")
            {
                var data = db.Cars.Where(x => x.carno == Search).ToList();
                return View(data);
            }
            else if (SearchBy == "Model")
            {
                var data = db.Cars.Where(x => x.model == Search).ToList();
                return View(data);
            }
            else
            {
                var data = db.Cars.ToList();
                return View(data);
            }
        }
        // GET: Cars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // GET: Cars/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,carno,make,model,available")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Cars.Add(car);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(car);
        }

        // GET: Cars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,carno,make,model,available")] Car car)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Car car = db.Cars.Find(id);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Car car = db.Cars.Find(id);
            db.Cars.Remove(car);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ISHTIAQ/Views/Cars/Create.cshtml
@model ISHTIAQ.Models.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.carno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.carno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ISHTIAQ/Views/Cars/Delete.cshtml
@model ISHTIAQ.Models.Car

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.carno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.available)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ISHTIAQ/Views/Cars/Details.cshtml
@model ISHTIAQ.Models.Car

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.carno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.carno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.available)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.available)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ISHTIAQ/Views/Cars/Edit.cshtml
@model ISHTIAQ.Models.Car

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Car</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.carno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.carno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.available, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.available, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.available, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ISHTIAQ/Views/Cars/Index.cshtml
@model IEnumerable<ISHTIAQ.Models.Car>

@{
    ViewBag.Title = "Index";
}
<h2>Car Details</h2>

@using (Html.BeginForm("Index", "Cars", FormMethod.Get))
{
    <b>SearchBy: </b> @Html.RadioButton("SearchBy", "Number", true)<text>   Number   </text>
    @Html.RadioButton("SearchBy", "Model")<text >   Model   </text>

    @Html.TextBox("Search") <input class="bg-primary" type="submit" value="Search" />
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered table-responsive-md table-striped text-center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.carno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.make)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.available)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.carno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.available)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>